FROM node:20 AS builder
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm install
COPY . .


RUN npm run build
FROM node:20-slim
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app ./dist
COPY --from=builder /usr/src/app/package.json ./
COPY --from=builder /usr/src/app/package-lock.json ./
EXPOSE 5050
CMD ["npm", "start"]